package ru.park.mail.java.sample23lambda;

public enum Role {
	GOALKEEPER, DEFENDER, CENTER_BACK, SWEEPER, RIGHT_BACK, LEFT_BACK, RIGHT_WINGBACK,
    LEFT_WINGBACK, MIDFIELDER, DEFENSIVE_MIDFIELDER, CENTER_MIDFIELDER, ATTACKING_MIDFIELDER,
    LEFT_MIDFIELDER, RIGHT_MIDFIELDER, FORWARD, STRIKER, SECOND_STRIKER, RIGHT_WINGER, LEFT_WINGER,
    RIGHT_FORWARD, LEFT_FORWARD, CENTER_FORWARD;
}
